---
# Elasticsearch Ansible Playbook
# Configure and deploy elasticsearch on elasticsearch nodes.
- hosts: elastic
  remote_user: root
  roles:
   - java
   - elasticsearch

# Configure nginx as es-nodes load balancer. Install kibana.
- hosts: balancer
  remote_user: root
  roles:
   - nginx
   - kibana
