---
# DigitalOcean SSH key settings
# -----------------------------
# This is the human-readable display name for the given SSH key.
digitalocean_ssh_name: "{{ lookup('env', 'USER') }}"
# The path to the public key.
digitalocean_ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
# The path to the private key.
digitalocean_ssh_private_key: "{{ lookup('file', '~/.ssh/id_rsa') }}"

# DigitalOcean droplets settings
# -----------------------------
digitalocean_droplets:
  - name: elastic-node01
    size: 512mb
    region: fra1
    image: ubuntu-14-04-x64

  - name: elastic-node02
    size: 512mb
    region: fra1
    image: ubuntu-14-04-x64

  - name: elastic-node03
    size: 512mb
    region: fra1
    image: ubuntu-14-04-x64

  - name: elastic-node04
    size: 512mb
    region: fra1
    image: ubuntu-14-04-x64
  
  - name: balancer-nginx
    size: 2gb
    region: fra1
    image: ubuntu-14-04-x64
