---
- name: WebUpd8 apt repo
  apt_repository: repo='ppa:webupd8team/java' update_cache=yes

- name: Accept Oracle license
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Java apt packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600 state=present
  with_items:
   - oracle-java8-installer
   - oracle-java8-set-default
